ComicBookGallery/ComicBookGallery/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBookGallery.Models
{
    public class Artist
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

ComicBookGallery/ComicBookGallery/Models/ComicBook.cs
namespace ComicBookGallery.Models
{
    public class ComicBook
    {
        public int Id { get; set; }
        public string SeriesTitle { get; set; }
        public int IssueNumber { get; set; }
        public string DescriptionHtml { get; set; }
        public Artist[] Artists { get; set; }
        public bool Favorite { get; set; }

        public string DisplayText
        {
            get { return SeriesTitle + " #" + IssueNumber; }
        }

        // series-title-issuenumber.jpg
        public string CoverImageFileName
        {
            get { return SeriesTitle.Replace(" ", "-").ToLower() + "-" + IssueNumber + ".jpg"; }
        }

    }
}

ComicBookGallery/ComicBookGallery/Controllers/ComicBooksController.cs
using System.Web.Mvc;
using ComicBookGallery.Data;
using ComicBookGallery.Models;

namespace ComicBookGallery.Controllers
{
    public class ComicBooksController : Controller
    {
        private readonly ComicBookRepository _comicBookRepository;

        public ComicBooksController()
        {
            _comicBookRepository = new ComicBookRepository();
        }

        public ActionResult Index()
        {
            ComicBook[] comicBooks = _comicBookRepository.GetComicBooks();
            return View(comicBooks);
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            ComicBook comicBook = _comicBookRepository.GetComicBook((int)id);
            return View(comicBook);
        }
    }
}

ComicBookGallery/ComicBookGallery/Views/ComicBooks/Detail.cshtml
@using ComicBookGallery.Models

@{
    ViewBag.Title = Model.DisplayText;
    ViewBag.ShowBackBar = true;
}

<h2>@Model.DisplayText</h2>

<div class="row">
    <div class="col-md-6">
        <div class="well">
            <h5><label>Series Title:</label> @Model.SeriesTitle</h5>
            <h5><label>Issue #:</label> @Model.IssueNumber</h5>
            <h5><label>Favorite:</label> @(Model.Favorite ? "Yes" : "No")</h5>
            @if (Model.Artists.Length > 0)
            {
                <h5>Artist:</h5>
                <div>
                    <ul>
                        @foreach (Artist artist in Model.Artists)
                        {
                            <li>@artist.Role: @artist.Name</li>
                        }
                    </ul>
                </div>
            }
        </div>
        <h5>Description</h5>
        <div>@Html.Raw(Model.DescriptionHtml)</div>
    </div>
    <div class="col-md-6">
        <img src="/Images/@Model.CoverImageFileName"
             alt="@Model.DisplayText" class="img-responsive"/>
    </div>
</div>
    

ComicBookGallery/ComicBookGallery/Views/ComicBooks/Index.cshtml
@using ComicBookGallery.Models
@model ComicBookGallery.Models.ComicBook[] 

@{
    ViewBag.Title = "Comic Books";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    @foreach (ComicBook comicBook in Model)
    {
        <div class="col-md-3">
            <h4>@Html.ActionLink(comicBook.DisplayText, "Detail", new {id = comicBook.Id})</h4>
            <a href="@Url.Action("Detail", new {id = comicBook.Id})">
                <img src="/Images/@comicBook.CoverImageFileName"
                     alt="@comicBook.DisplayText"
                     class="img-responsive" />
            </a>
        </div>

    }
    
</div>

ComicBookGallery/ComicBookGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Comic Book Gallery</title>
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Comic Book Gallery", "Index", "ComicBooks", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- Add menu items here -->
                </ul>
            </div>
        </div>
    </div>

    @if (ViewBag.ShowBackBar != null && ViewBag.ShowBackBar)
    {
        <div class="backbar">
            <div class="container">
                @Html.ActionLink("Return to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    }

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Comic Book Gallery</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>